### ISSUE TITLE
version 0.8

### ISSUE THREAD

**Issue by MaximeBouton** [tawheeler/AutomotiveDrivingModels.jl#66]
As AutoViz is moving towards a version 0.8 maybe this package should move on as well. 
Here is a description of stuff to do: 
- [x] merge #64 
- [x] make Vec.jl a submodule #76 
- [x] incoroporate Records.jl #78 
- [x] new feature extraction mechanism #72 
- [x] use literate to run tutorials in the test suite #77
- [x] rename `Frame` to `Scene`
- [x] rename `get_...` functions #74 (some of them)
- [x] Rename to AutomotiveSimulator.jl 
- [x] Register AutomotiveSimulator.jl to sisl Registry with documentation tests commented 
- [x] Fix AutoViz, rename AutoViz
- [x] Register to general lose #56 
- [x] Register AutomotiveVisualization.jl to general 
- [x] Restore doc tests in AutomotiveSimulator.jl

Drop support for deprecated functions:
- [x] simulate 
- [x] state1D 
- [x] get_name
- [x] `Scene` and `Vehicle` aliases

**Comment by mattuntergassmair** [comment]
#64 is now ready to review

As for `State1D`, what is the main reason we are dropping it? I have not used it before but one case where I think it could be useful would be for macroscopic traffic simulations on large road networks, where overall traffic flow is modeled. Also, it is currently used for the Straight Rowadway example in the docs so if we drop it we should re-write that example for 2D vehicles. 
I was able to make `State1D` work with the new interface by introducing `posf`, `posg`, are there other aspects which make it unuseable in the new interface?
PR #64 currently needs support for `State1D` for the straight roadway example, but we can delete it if we re-do the Straight Roadway example.

**Comment by mattuntergassmair** [comment]
What is the reason for deprecating `get_name` and are there alternatives?

**Comment by MaximeBouton** [comment]
I don't think there is any use for `get_name`. 
The case for `State1D` is arguable but I am not super convinced...

**Comment by mattuntergassmair** [comment]
> I don't think there is any use for `get_name`.
> The case for `State1D` is arguable but I am not super convinced...

I was using `get_name` in my GUI to display the model which each of the agents is following (including model parameters), i.e. `IDM s0 2.0 T 1.5` or similar. Could easily work around to make it work without `get_name`, just want to make sure we are certain about deprecating it.
Same for State1D but as mentioned earlier for macroscopic simulations State1D may be more lightweight

**Comment by MaximeBouton** [comment]
I think `typeof` would work in that case?

**Comment by mattuntergassmair** [comment]
In some cases you may want something more specific than `typeof`, such as `IDM s0 2.0 T 1.5` instead of `IntelligentDriverModel`. But I think I am also in favor of removing `get_name` from the interface - users can always implement `get_name` for the models of interest outside of ADM.

**Comment by MaximeBouton** [comment]
https://github.com/sisl/AutomotiveSimulator.jl
https://github.com/sisl/AutomotiveVisualization.jl
